version: '3.3'

services:

  app1:
    build:
      context: ./app1
    image: network-test-app1
    networks:
      vlan10:
        ipv4_address: 192.168.1.73
    restart: unless-stopped
    volumes:
      - ./app1:/opt/app
    environment:
      NODE_ENV: "development"

networks:
  vlan10:
    driver: macvlan
    driver_opts:
      parent: eth0.10
    ipam:
      config:
        - subnet: 192.168.1.0/24
