version: '3.3'

services:

  app1:
    build:
      context: ./app1
    image: network-test-app1
    networks:
      - vlan87
    restart: unless-stopped
    volumes:
      - ./app1:/opt/app
    environment:
      NODE_ENV: "development"

networks:
  vlan87:
    driver: macvlan
    driver_opts:
      parent: eth1.87
    ipam:
      config:
        - subnet: 10.25.87.0/24
          gateway: 10.25.87.1
          ip_range: 10.25.87.32/28 # IP from this pool are assigned automatically
